### ISSUE TITLE
`check` fails with NullPointerException

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty-ecosystem#1]
```
> check
>>> check
>>> updateDotty
[info] Pulling the latest Dotty changes
[info] Updating Dotty submodules. If working against a fresh clone, this might take a few minutes.
$ git submodule sync
Synchronizing submodule url for 'community-build/community-projects/ScalaPB'
Synchronizing submodule url for 'community-build/community-projects/algebra'
Synchronizing submodule url for 'community-build/community-projects/betterfiles'
Synchronizing submodule url for 'community-build/community-projects/dotty-cps-async'
Synchronizing submodule url for 'community-build/community-projects/effpi'
Synchronizing submodule url for 'community-build/community-projects/fastparse'
Synchronizing submodule url for 'community-build/community-projects/geny'
Synchronizing submodule url for 'community-build/community-projects/intent'
Synchronizing submodule url for 'community-build/community-projects/minitest'
Synchronizing submodule url for 'community-build/community-projects/munit'
Synchronizing submodule url for 'community-build/community-projects/os-lib'
Synchronizing submodule url for 'community-build/community-projects/pdbp'
Synchronizing submodule url for 'community-build/community-projects/scala-parser-combinators'
Synchronizing submodule url for 'community-build/community-projects/scala-xml'
Synchronizing submodule url for 'community-build/community-projects/scalacheck'
Synchronizing submodule url for 'community-build/community-projects/scalap'
Synchronizing submodule url for 'community-build/community-projects/scalatest'
Synchronizing submodule url for 'community-build/community-projects/scalatestplus-scalacheck'
Synchronizing submodule url for 'community-build/community-projects/scodec'
Synchronizing submodule url for 'community-build/community-projects/scodec-bits'
Synchronizing submodule url for 'community-build/community-projects/sconfig'
Synchronizing submodule url for 'community-build/community-projects/scopt'
Synchronizing submodule url for 'community-build/community-projects/shapeless'
Synchronizing submodule url for 'community-build/community-projects/sourcecode'
Synchronizing submodule url for 'community-build/community-projects/squants'
Synchronizing submodule url for 'community-build/community-projects/stdLib213'
Synchronizing submodule url for 'community-build/community-projects/upickle'
Synchronizing submodule url for 'community-build/community-projects/utest'
Synchronizing submodule url for 'community-build/community-projects/xml-interpolator'
Synchronizing submodule url for 'community-build/community-projects/zio'
$ git submodule update
null
java.lang.NullPointerException
	at ecosystem.checkProject$package$.buildCiTrackingCache$$anonfun$1(checkProject.scala:51)
	at ecosystem.model.Project$package$.doWithGit(Project.scala:48)
	at ecosystem.model.Project$package$extension_dir_Project$.withGit(Project.scala:56)
	at ecosystem.checkProject$package$.buildCiTrackingCache(checkProject.scala:52)
	at ecosystem.executeCommand$package$.executeCommand(executeCommand.scala:34)
	at ecosystem.impl.Repl$package$.handle(Repl.scala:41)
	at ecosystem.impl.Repl$package$.loop$1(Repl.scala:29)
	at ecosystem.impl.Repl$package$.Repl(Repl.scala:34)
	at ecosystem.impl.Repl.main(Repl.scala:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)
>
```

**Comment by larsrh** [comment]
For me it fails with `NoSuchElementException`:

```
> check
>>> check
>>> updateDotty
[info] Pulling the latest Dotty changes
[info] Updating Dotty submodules. If working against a fresh clone, this might take a few minutes.
$ git submodule sync
Synchronizing submodule url for 'community-build/community-projects/ScalaPB'
Synchronizing submodule url for 'community-build/community-projects/algebra'
Synchronizing submodule url for 'community-build/community-projects/betterfiles'
Synchronizing submodule url for 'community-build/community-projects/dotty-cps-async'
Synchronizing submodule url for 'community-build/community-projects/effpi'
Synchronizing submodule url for 'community-build/community-projects/endpoints'
Synchronizing submodule url for 'community-build/community-projects/fastparse'
Synchronizing submodule url for 'community-build/community-projects/geny'
Synchronizing submodule url for 'community-build/community-projects/intent'
Synchronizing submodule url for 'community-build/community-projects/minitest'
Synchronizing submodule url for 'community-build/community-projects/munit'
Synchronizing submodule url for 'community-build/community-projects/os-lib'
Synchronizing submodule url for 'community-build/community-projects/pdbp'
Synchronizing submodule url for 'community-build/community-projects/scala-parser-combinators'
Synchronizing submodule url for 'community-build/community-projects/scala-xml'
Synchronizing submodule url for 'community-build/community-projects/scalacheck'
Synchronizing submodule url for 'community-build/community-projects/scalap'
Synchronizing submodule url for 'community-build/community-projects/scalatest'
Synchronizing submodule url for 'community-build/community-projects/scalatestplus-scalacheck'
Synchronizing submodule url for 'community-build/community-projects/scalaz'
Synchronizing submodule url for 'community-build/community-projects/scas'
Synchronizing submodule url for 'community-build/community-projects/scodec'
Synchronizing submodule url for 'community-build/community-projects/scodec-bits'
Synchronizing submodule url for 'community-build/community-projects/sconfig'
Synchronizing submodule url for 'community-build/community-projects/scopt'
Synchronizing submodule url for 'community-build/community-projects/shapeless'
Synchronizing submodule url for 'community-build/community-projects/sourcecode'
Synchronizing submodule url for 'community-build/community-projects/squants'
Synchronizing submodule url for 'community-build/community-projects/stdLib213'
Synchronizing submodule url for 'community-build/community-projects/upickle'
Synchronizing submodule url for 'community-build/community-projects/utest'
Synchronizing submodule url for 'community-build/community-projects/xml-interpolator'
Synchronizing submodule url for 'community-build/community-projects/zio'
$ git submodule update
null
java.util.NoSuchElementException
        at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:604)
        at scala.collection.immutable.HashMap.apply(HashMap.scala:131)
        at ecosystem.checkProject$package$.checkProject$$anonfun$1(checkProject.scala:26)
        at ecosystem.model.Project$package$.doWithGit(Project.scala:48)
        at ecosystem.model.Project$package$extension_dir_Project$.withGit(Project.scala:56)
        at ecosystem.checkProject$package$.checkProject(checkProject.scala:43)
        at ecosystem.executeCommand$package$.$anonfun$1(executeCommand.scala:39)
        at scala.collection.immutable.List.map(List.scala:223)
        at ecosystem.executeCommand$package$.executeCommand(executeCommand.scala:39)
        at ecosystem.impl.Repl$package$.handle(Repl.scala:41)
        at ecosystem.impl.Repl$package$.loop$1(Repl.scala:29)
        at ecosystem.impl.Repl$package$.Repl(Repl.scala:34)
        at ecosystem.impl.Repl.main(Repl.scala:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.Run.invokeMain(Run.scala:115)
        at sbt.Run.execute$1(Run.scala:79)
        at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
        at sbt.TrapExit$App.run(TrapExit.scala:257)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
